app:
  jwt:
    expiration: ${JWT_EXPIRATION:1800000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000}
    issuer: ${JWT_ISSUER:auth-service}
    key-id: ${JWT_KEY_ID:key-id}
server:
  port: ${SERVER_PORT:9393}
spring:
  cloud:
    vault:
      uri: ${VAULT_URI:http://localhost:8200}
      token: ${VAULT_TOKEN:token}
      kv:
        backend: ${VAULT_KV_BACKEND:life-simulator}
        application-name: ${VAULT_KV_NAME:auth}
        default-context:
  config:
    import: ${VAULT_CONFIG_IMPORT:vault:///life-simulator/auth}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/lifesim_auth_dev}
    username: ${DATASOURCE_USERNAME:dev}
    password: ${DATASOURCE_PASSWORD:dev}
    driver-class-name: ${DATASOURCE_DRIVER_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:true}
  security:
    oauth2:
      authorizationserver:
        issuer: ${OAUTH2_SERVER_ISSUER:http://localhost:9393}
  application:
    name: auth-service
logging:
  level:
    org.springframework.web: debug