name: life-simulator

services:
  vault:
    build:
      context: ./vault/config
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault/data:/vault/data:ro
      - ./vault/config/vault.hcl:/vault/config/vault.hcl:ro
    cap_add:
      - IPC_LOCK
    env_file:
      - ./vault/config/.env
    command: server
    restart: unless-stopped

  kafka:
    build:
      context: ./kafka/config
      dockerfile: Dockerfile
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - ./kafka/config/.env

  kafka-ui:
    build:
      context: ./kafka/config/ui
      dockerfile: Dockerfile
    container_name: kafka-ui
    ports:
      - "8585:8080"
    env_file:
      - ./kafka/config/ui/.env
    depends_on:
      - kafka

  eureka:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka-service
    ports:
      - "8761:8761"
    env_file:
      - ./eureka-service/.env
    restart: unless-stopped

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "9696:9696"
    env_file:
      - ./gateway-service/.env
    restart: unless-stopped

networks:
  life-simulator-network:
    driver: bridge
    name: life-simulator-network