name: life-simulator

services:
  vault:
    build:
      context: ./vault/config
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
      - ./vault/config/vault.hcl:/vault/config/vault.hcl:ro
    cap_add:
      - IPC_LOCK
    env_file:
      - ./vault/config/.env
    command: server
    restart: unless-stopped

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "6432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./postgres/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    build:
      context: ./kafka/config
      dockerfile: Dockerfile
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
      - ./kafka/logs:/var/log/kafka
    env_file:
      - ./kafka/config/.env
    restart: unless-stopped

  kafka-ui:
    build:
      context: ./kafka/config/ui
      dockerfile: Dockerfile
    container_name: kafka-ui
    ports:
      - "8585:8080"
    env_file:
      - ./kafka/config/ui/.env
    depends_on:
      - kafka
    restart: unless-stopped

  eureka:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka-service
    ports:
      - "8761:8761"
    volumes:
      - ./eureka-service/logs:/app/logs
    env_file:
      - ./eureka-service/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "9696:9696"
    volumes:
      - ./gateway-service/logs:/app/logs
    env_file:
      - ./gateway-service/.env
    depends_on:
      eureka:
        condition: service_healthy
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "9393:9393"
    volumes:
      - ./auth-service/logs:/app/logs
    env_file:
      - ./auth-service/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped