app:
  mode: dev
  tick-rate: 3000
  jwt:
    issuer: auth-service
server:
  port: 9595
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:9393/.well-known/jwks.json
  application:
    name: time-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: life-sim
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer