server:
  port: 9595
  tomcat:
    threads:
      max: 4
spring:
  application:
    name: time-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: life-sim
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer