[versions]
kotlin = "2.2.21"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
springBoot = "4.0.1"
liquibase = "5.0.1"
postgresql = "42.7.9"
jackson = "3.0.4"
jjwt = "0.13.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

springboot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }
springboot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
springboot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }
springboot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
springboot-starter-liquibase = { module = "org.springframework.boot:spring-boot-starter-liquibase", version.ref = "springBoot" }
springboot-kafka-starter = { module = "org.springframework.boot:spring-boot-starter-kafka", version.ref = "springBoot" }
springboot-kafka = { module = "org.springframework.kafka:spring-kafka", version.ref = "springBoot" }
springboot-server-tomcat = { module = "org.springframework.boot:spring-boot-starter-tomcat", version.ref = "springBoot" }
postgresql-jdbc = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
migration-liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-jackson = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-gson = { module = "io.jsonwebtoken:jjwt-gson", version.ref = "jjwt" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }

[bundles]
kotlinx-ecosystem = ["kotlinx-datetime", "kotlinx-serialization", "kotlinx-coroutines"]

springboot-security-ecosystem = [
    "springboot-starter-data-jpa",
    "springboot-starter-web",
    "springboot-starter-actuator",
    "springboot-starter-security",
    "springboot-server-tomcat",
    "kotlin-jackson",
]

springboot-kafka-ecosystem = [
    "springboot-starter-web",
    "springboot-starter-actuator",
    "springboot-kafka-starter",
    "springboot-kafka",
    "springboot-server-tomcat",
    "kotlin-jackson",
]