[versions]
kotlin = "2.3.10"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
springBoot = "4.0.1"
springDependencyManagement = "1.1.7"
springCloud = "5.0.1"
liquibase = "5.0.1"
postgresql = "42.7.9"
jackson = "3.0.4"
jjwt = "0.13.0"
openapiUi = "3.0.1"
vaultConfig = "5.0.1"
vaultCore = "4.0.0"
protobuf = "1.10.0"
mockk = "1.14.9"
testContainersPostgresql = "1.21.4"
caffeineCache = "3.2.3"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

springboot-starter-vault-config = { module = "org.springframework.cloud:spring-cloud-starter-vault-config", version.ref = "vaultConfig" }
springframework-vault-core = { module = "org.springframework.vault:spring-vault-core", version.ref = "vaultCore" }

springboot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }
springboot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
springboot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }

springboot-starter-gateway = { module = "org.springframework.cloud:spring-cloud-starter-gateway-server-webmvc", version.ref = "springCloud" }
springboot-starter-loadbalancer = { module = "org.springframework.cloud:spring-cloud-starter-loadbalancer", version.ref = "springCloud" }
springboot-starter-eureka-client = { module = "org.springframework.cloud:spring-cloud-starter-netflix-eureka-client", version.ref = "springCloud" }
springboot-starter-eureka-server = { module = "org.springframework.cloud:spring-cloud-starter-netflix-eureka-server", version.ref = "springCloud" }

springboot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
springboot-starter-liquibase = { module = "org.springframework.boot:spring-boot-starter-liquibase", version.ref = "springBoot" }
springboot-starter-springdoc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "openapiUi" }
springboot-starter-oauth2-authorization-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-authorization-server", version.ref = "springBoot" }
springboot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server", version.ref = "springBoot" }
springboot-starter-mail = { module = "org.springframework.boot:spring-boot-starter-mail", version.ref = "springBoot" }
springboot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "springBoot" }
springboot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache", version.ref = "springBoot" }
springboot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }

caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeineCache" }

springboot-kafka-starter = { module = "org.springframework.boot:spring-boot-starter-kafka", version.ref = "springBoot" }
springboot-kafka = { module = "org.springframework.kafka:spring-kafka", version.ref = "springBoot" }
springboot-server-tomcat = { module = "org.springframework.boot:spring-boot-starter-tomcat", version.ref = "springBoot" }

springboot-data-jpa-test = { module = "org.springframework.boot:spring-boot-data-jpa-test", version.ref = "springBoot" }
springboot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springBoot" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testContainersPostgresql" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testContainersPostgresql" }

postgresql-jdbc = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
migration-liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-jackson = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-gson = { module = "io.jsonwebtoken:jjwt-gson", version.ref = "jjwt" }

kotlin-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "protobuf" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }

[bundles]
kotlinx-ecosystem = ["kotlinx-datetime", "kotlinx-serialization", "kotlinx-coroutines"]

springboot-security-ecosystem = [
    "springboot-starter-data-jpa",
    "springboot-starter-web",
    "springboot-starter-actuator",
    "springboot-starter-security",
    "springboot-starter-oauth2-authorization-server",
    "springboot-server-tomcat",
    "kotlin-jackson",
]

springboot-kafka-ecosystem = [
    "springboot-starter-web",
    "springboot-starter-actuator",
    "springboot-kafka-starter",
    "springboot-kafka",
    "springboot-server-tomcat",
    "kotlin-jackson",
]