server:
  port: ${SERVER_PORT:9292}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:8761/eureka/}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_RESOURCE_SERVER_JWK_URI:http://auth-service:9393/.well-known/jwks.json}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/lifesim_character}
    username: ${DATASOURCE_USERNAME:dev}
    password: ${DATASOURCE_PASSWORD:dev}
    driver-class-name: ${DATASOURCE_DRIVER_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:true}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:character-consumer}
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      key-deserializer: ${KAFKA_CONSUMER_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
      value-deserializer: ${KAFKA_CONSUMER_VALUE_DESERIALIZER:ru.woowy.infrastructure.serialization.EventDeserializer}
    producer:
      key-serializer: ${KAFKA_PRODUCER_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      value-serializer: ${KAFKA_PRODUCER_VALUE_SERIALIZER:ru.woowy.infrastructure.serialization.EventSerializer}
  application:
    name: character-service