name: Release

on:
  push:
    branches:
      - main

jobs:
  release-auth:
    uses: ./.github/workflows/release-service.yml
    with:
      service: auth-service
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release-gateway:
    needs: release-auth
    uses: ./.github/workflows/release-service.yml
    with:
      service: gateway-service
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release-eureka:
    needs: release-gateway
    uses: ./.github/workflows/release-service.yml
    with:
      service: eureka-service
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release-notification:
    needs: release-eureka
    uses: ./.github/workflows/release-service.yml
    with:
      service: notification-service
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release-world:
    needs: release-notification
    uses: ./.github/workflows/release-service.yml
    with:
      service: world-service
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release-character:
    needs: release-world
    uses: ./.github/workflows/release-service.yml
    with:
      service: character-service
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release-engine:
    needs: release-character
    uses: ./.github/workflows/release-service.yml
    with:
      service: engine-service
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release-need:
    needs: release-engine
    uses: ./.github/workflows/release-service.yml
    with:
      service: need-service
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}